export type N8nNodeGroup = "trigger" | "input" | "transform" | "output";

export type N8nConnectionRole =
  | "main"
  | "ai-model"
  | "ai-parser"
  | "ai-tool"
  | "ai-memory";

export interface N8nNodeCatalogEntry {
  key: string;
  nodeName: string;
  type: string;
  displayName: string;
  category: string;
  group: N8nNodeGroup;
  description: string;
  capabilities: string[];
  version: number;
  connectionRole: N8nConnectionRole;
  requiresAiModel?: boolean;
  isFallback?: boolean;
}

export const N8N_NODE_CATALOG: readonly N8nNodeCatalogEntry[] = [
  {
    key: "manualTrigger",
    nodeName: "manualTrigger",
    type: "n8n-nodes-base.manualTrigger",
    displayName: "Manual Trigger",
    category: "Core Nodes",
    group: "trigger",
    description: "Start a workflow manually from the n8n editor.",
    capabilities: ["manual start", "test workflow", "run on demand"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "scheduleTrigger",
    nodeName: "scheduleTrigger",
    type: "n8n-nodes-base.scheduleTrigger",
    displayName: "Schedule Trigger",
    category: "Core Nodes",
    group: "trigger",
    description: "Start a workflow at a defined time or recurring interval.",
    capabilities: ["run every morning", "run daily", "run weekly", "scheduled automation"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "webhook",
    nodeName: "webhook",
    type: "n8n-nodes-base.webhook",
    displayName: "Webhook",
    category: "Core Nodes",
    group: "trigger",
    description: "Start a workflow when an HTTP webhook request is received.",
    capabilities: ["receive HTTP request", "API endpoint", "external event trigger", "form submission"],
    version: 2,
    connectionRole: "main",
  },
  {
    key: "chatTrigger",
    nodeName: "chatTrigger",
    type: "@n8n/n8n-nodes-langchain.chatTrigger",
    displayName: "Chat Trigger",
    category: "Core Nodes",
    group: "trigger",
    description: "Start a workflow when a message is submitted through n8n chat.",
    capabilities: ["chatbot input", "chat message trigger", "conversational workflow"],
    version: 1.4,
    connectionRole: "main",
  },
  {
    key: "gmailTrigger",
    nodeName: "gmailTrigger",
    type: "n8n-nodes-base.gmailTrigger",
    displayName: "Gmail Trigger",
    category: "Communication",
    group: "trigger",
    description: "Start a workflow when matching Gmail events or messages are detected.",
    capabilities: ["new Gmail message", "email received", "watch Gmail inbox"],
    version: 1.3,
    connectionRole: "main",
  },
  {
    key: "microsoftOutlookTrigger",
    nodeName: "microsoftOutlookTrigger",
    type: "n8n-nodes-base.microsoftOutlookTrigger",
    displayName: "Microsoft Outlook Trigger",
    category: "Communication",
    group: "trigger",
    description: "Start a workflow when matching Microsoft Outlook events occur.",
    capabilities: ["new Outlook email", "email received", "watch Outlook inbox"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "gmail",
    nodeName: "gmail",
    type: "n8n-nodes-base.gmail",
    displayName: "Gmail",
    category: "Communication",
    group: "transform",
    description: "Read, search, send, label, and manage Gmail messages.",
    capabilities: ["read Gmail messages", "search email", "get many emails", "send email", "reply to email"],
    version: 2.2,
    connectionRole: "main",
  },
  {
    key: "microsoftOutlook",
    nodeName: "microsoftOutlook",
    type: "n8n-nodes-base.microsoftOutlook",
    displayName: "Microsoft Outlook",
    category: "Communication",
    group: "transform",
    description: "Read, create, send, and manage Microsoft Outlook data.",
    capabilities: ["read Outlook email", "send Outlook email", "manage Outlook messages", "work with Outlook calendar"],
    version: 2,
    connectionRole: "main",
  },
  {
    key: "slack",
    nodeName: "slack",
    type: "n8n-nodes-base.slack",
    displayName: "Slack",
    category: "Communication",
    group: "output",
    description: "Send messages and work with Slack channels and users.",
    capabilities: ["send Slack message", "notify team", "post to channel"],
    version: 2.3,
    connectionRole: "main",
  },
  {
    key: "microsoftTeams",
    nodeName: "microsoftTeams",
    type: "n8n-nodes-base.microsoftTeams",
    displayName: "Microsoft Teams",
    category: "Communication",
    group: "transform",
    description: "Send messages and work with Microsoft Teams.",
    capabilities: ["send Teams message", "notify Microsoft Teams", "post to Teams channel"],
    version: 2,
    connectionRole: "main",
  },
  {
    key: "discord",
    nodeName: "discord",
    type: "n8n-nodes-base.discord",
    displayName: "Discord",
    category: "Communication",
    group: "output",
    description: "Send messages and manage Discord resources.",
    capabilities: ["send Discord message", "post to Discord channel", "Discord notification"],
    version: 2,
    connectionRole: "main",
  },
  {
    key: "googleSheets",
    nodeName: "googleSheets",
    type: "n8n-nodes-base.googleSheets",
    displayName: "Google Sheets",
    category: "Productivity",
    group: "transform",
    description: "Read, append, update, and manage spreadsheet data in Google Sheets.",
    capabilities: ["read spreadsheet", "append row", "update row", "store tabular data"],
    version: 4.7,
    connectionRole: "main",
  },
  {
    key: "googleDrive",
    nodeName: "googleDrive",
    type: "n8n-nodes-base.googleDrive",
    displayName: "Google Drive",
    category: "Data & Storage",
    group: "transform",
    description: "Find, upload, download, move, and manage files in Google Drive.",
    capabilities: ["find files", "upload file", "download file", "manage Google Drive"],
    version: 3,
    connectionRole: "main",
  },
  {
    key: "googleCalendar",
    nodeName: "googleCalendar",
    type: "n8n-nodes-base.googleCalendar",
    displayName: "Google Calendar",
    category: "Productivity",
    group: "transform",
    description: "Create, read, update, and manage Google Calendar events.",
    capabilities: ["create calendar event", "schedule meeting", "read calendar", "update event"],
    version: 1.3,
    connectionRole: "main",
  },
  {
    key: "notion",
    nodeName: "notion",
    type: "n8n-nodes-base.notion",
    displayName: "Notion",
    category: "Productivity",
    group: "transform",
    description: "Read, create, update, and manage Notion pages and database records.",
    capabilities: ["create Notion page", "create database record", "update Notion record", "create internal task"],
    version: 2.2,
    connectionRole: "main",
  },
  {
    key: "airtable",
    nodeName: "airtable",
    type: "n8n-nodes-base.airtable",
    displayName: "Airtable",
    category: "Data & Storage",
    group: "input",
    description: "Read, create, update, and delete Airtable records.",
    capabilities: ["read Airtable records", "create Airtable record", "update Airtable record"],
    version: 2.2,
    connectionRole: "main",
  },
  {
    key: "asana",
    nodeName: "asana",
    type: "n8n-nodes-base.asana",
    displayName: "Asana",
    category: "Productivity",
    group: "input",
    description: "Create and manage tasks, projects, and comments in Asana.",
    capabilities: ["create Asana task", "manage tasks", "create internal review task"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "trello",
    nodeName: "trello",
    type: "n8n-nodes-base.trello",
    displayName: "Trello",
    category: "Productivity",
    group: "transform",
    description: "Create and manage Trello cards, lists, and boards.",
    capabilities: ["create Trello card", "manage task board", "create internal task"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "jira",
    nodeName: "jira",
    type: "n8n-nodes-base.jira",
    displayName: "Jira Software",
    category: "Productivity",
    group: "transform",
    description: "Create and manage Jira issues, comments, and projects.",
    capabilities: ["create Jira issue", "update Jira issue", "create engineering task"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "httpRequest",
    nodeName: "httpRequest",
    type: "n8n-nodes-base.httpRequest",
    displayName: "HTTP Request",
    category: "Core Nodes",
    group: "output",
    description: "Call an HTTP API when no more specific native integration is available.",
    capabilities: ["call REST API", "send HTTP request", "connect unsupported service", "call internal API"],
    version: 4.2,
    connectionRole: "main",
    isFallback: true,
  },
  {
    key: "code",
    nodeName: "code",
    type: "n8n-nodes-base.code",
    displayName: "Code",
    category: "Core Nodes",
    group: "transform",
    description: "Run custom JavaScript or Python for deterministic data transformation.",
    capabilities: ["custom deterministic logic", "reshape data", "calculate values", "normalize data"],
    version: 2,
    connectionRole: "main",
    isFallback: true,
  },
  {
    key: "set",
    nodeName: "set",
    type: "n8n-nodes-base.set",
    displayName: "Edit Fields",
    category: "Core Nodes",
    group: "transform",
    description: "Add, remove, rename, or set fields without custom code.",
    capabilities: ["edit fields", "set values", "rename fields", "prepare payload"],
    version: 3.4,
    connectionRole: "main",
  },
  {
    key: "if",
    nodeName: "if",
    type: "n8n-nodes-base.if",
    displayName: "If",
    category: "Core Nodes",
    group: "transform",
    description: "Split a workflow into true and false branches using conditions.",
    capabilities: ["conditional branch", "yes or no decision", "check value"],
    version: 2.2,
    connectionRole: "main",
  },
  {
    key: "switch",
    nodeName: "switch",
    type: "n8n-nodes-base.switch",
    displayName: "Switch",
    category: "Core Nodes",
    group: "transform",
    description: "Route workflow items into multiple branches based on rules.",
    capabilities: ["multi-branch routing", "route by category", "route by status"],
    version: 3.2,
    connectionRole: "main",
  },
  {
    key: "filter",
    nodeName: "filter",
    type: "n8n-nodes-base.filter",
    displayName: "Filter",
    category: "Core Nodes",
    group: "transform",
    description: "Keep only items that match defined conditions.",
    capabilities: ["filter items", "remove unrelated records", "keep matching data"],
    version: 2.2,
    connectionRole: "main",
  },
  {
    key: "merge",
    nodeName: "merge",
    type: "n8n-nodes-base.merge",
    displayName: "Merge",
    category: "Core Nodes",
    group: "transform",
    description: "Combine data or execution paths from multiple workflow branches.",
    capabilities: ["merge branches", "combine datasets", "join workflow paths"],
    version: 3.2,
    connectionRole: "main",
  },
  {
    key: "aggregate",
    nodeName: "aggregate",
    type: "n8n-nodes-base.aggregate",
    displayName: "Aggregate",
    category: "Core Nodes",
    group: "transform",
    description: "Combine values from multiple items into one item or list.",
    capabilities: ["aggregate items", "combine values", "create list"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "splitOut",
    nodeName: "splitOut",
    type: "n8n-nodes-base.splitOut",
    displayName: "Split Out",
    category: "Core Nodes",
    group: "transform",
    description: "Turn a list inside one item into separate workflow items.",
    capabilities: ["split array into items", "process list individually", "expand records"],
    version: 1,
    connectionRole: "main",
  },
  {
    key: "splitInBatches",
    nodeName: "splitInBatches",
    type: "n8n-nodes-base.splitInBatches",
    displayName: "Loop Over Items",
    category: "Core Nodes",
    group: "transform",
    description: "Process workflow items iteratively or in batches.",
    capabilities: ["loop over items", "process records one by one", "batch processing"],
    version: 3,
    connectionRole: "main",
  },
  {
    key: "wait",
    nodeName: "wait",
    type: "n8n-nodes-base.wait",
    displayName: "Wait",
    category: "Core Nodes",
    group: "transform",
    description: "Pause workflow execution until a time or resume condition is reached.",
    capabilities: ["delay workflow", "wait until date", "pause for approval", "resume later"],
    version: 1.1,
    connectionRole: "main",
  },
  {
    key: "agent",
    nodeName: "agent",
    type: "@n8n/n8n-nodes-langchain.agent",
    displayName: "AI Agent",
    category: "AI",
    group: "transform",
    description: "Generate an action plan and use connected tools to complete a multi-step task.",
    capabilities: ["AI agent", "tool-using assistant", "multi-step reasoning", "choose tools dynamically"],
    version: 1.3,
    connectionRole: "main",
    requiresAiModel: true,
  },
  {
    key: "chainLlm",
    nodeName: "chainLlm",
    type: "@n8n/n8n-nodes-langchain.chainLlm",
    displayName: "Basic LLM Chain",
    category: "AI",
    group: "transform",
    description: "Prompt a language model for generation, rewriting, analysis, or simple reasoning.",
    capabilities: ["generate text", "rewrite text", "summarize short text", "analyze content"],
    version: 1.9,
    connectionRole: "main",
    requiresAiModel: true,
  },
  {
    key: "chainSummarization",
    nodeName: "chainSummarization",
    type: "@n8n/n8n-nodes-langchain.chainSummarization",
    displayName: "Summarization Chain",
    category: "AI",
    group: "transform",
    description: "Transform text or documents into a concise summary.",
    capabilities: ["summarize text", "summarize email", "summarize document"],
    version: 2.1,
    connectionRole: "main",
    requiresAiModel: true,
  },
  {
    key: "informationExtractor",
    nodeName: "informationExtractor",
    type: "@n8n/n8n-nodes-langchain.informationExtractor",
    displayName: "Information Extractor",
    category: "AI",
    group: "transform",
    description: "Extract structured fields from unstructured text using a language model.",
    capabilities: ["extract structured fields", "extract candidate details", "parse email content", "convert text to JSON"],
    version: 1.2,
    connectionRole: "main",
    requiresAiModel: true,
  },
  {
    key: "textClassifier",
    nodeName: "textClassifier",
    type: "@n8n/n8n-nodes-langchain.textClassifier",
    displayName: "Text Classifier",
    category: "AI",
    group: "transform",
    description: "Classify text into one of several defined categories.",
    capabilities: ["classify priority", "categorize email", "detect intent", "route by semantic category"],
    version: 1.1,
    connectionRole: "main",
    requiresAiModel: true,
  },
  {
    key: "sentimentAnalysis",
    nodeName: "sentimentAnalysis",
    type: "@n8n/n8n-nodes-langchain.sentimentAnalysis",
    displayName: "Sentiment Analysis",
    category: "AI",
    group: "transform",
    description: "Analyze the sentiment expressed in text.",
    capabilities: ["detect sentiment", "analyze customer tone", "classify positive or negative text"],
    version: 1.1,
    connectionRole: "main",
    requiresAiModel: true,
  },
  {
    key: "outputParserStructured",
    nodeName: "outputParserStructured",
    type: "@n8n/n8n-nodes-langchain.outputParserStructured",
    displayName: "Structured Output Parser",
    category: "AI",
    group: "transform",
    description: "Require an AI node to return data in a defined JSON structure.",
    capabilities: ["structured AI output", "validate JSON format", "enforce output schema"],
    version: 1.3,
    connectionRole: "ai-parser",
  },
  {
    key: "lmChatOpenAi",
    nodeName: "lmChatOpenAi",
    type: "@n8n/n8n-nodes-langchain.lmChatOpenAi",
    displayName: "OpenAI Chat Model",
    category: "AI",
    group: "transform",
    description: "Provide an OpenAI chat model to a compatible AI root node.",
    capabilities: ["language model", "OpenAI model", "power AI chain", "power AI agent"],
    version: 1.3,
    connectionRole: "ai-model",
  },
  {
    key: "lmChatGoogleGemini",
    nodeName: "lmChatGoogleGemini",
    type: "@n8n/n8n-nodes-langchain.lmChatGoogleGemini",
    displayName: "Google Gemini Chat Model",
    category: "AI",
    group: "transform",
    description: "Provide a Google Gemini chat model to a compatible AI root node.",
    capabilities: ["language model", "Gemini model", "power AI chain", "power AI agent"],
    version: 1.1,
    connectionRole: "ai-model",
  },
  {
    key: "lmChatGroq",
    nodeName: "lmChatGroq",
    type: "@n8n/n8n-nodes-langchain.lmChatGroq",
    displayName: "Groq Chat Model",
    category: "AI",
    group: "transform",
    description: "Provide a Groq-hosted chat model to a compatible AI root node.",
    capabilities: ["language model", "Groq model", "fast AI inference", "power AI chain"],
    version: 1,
    connectionRole: "ai-model",
  },
] as const;

export type N8nNodeKey = (typeof N8N_NODE_CATALOG)[number]["key"];

export const N8N_NODE_BY_KEY: ReadonlyMap<string, N8nNodeCatalogEntry> =
  new Map(N8N_NODE_CATALOG.map((node) => [node.key, node]));

export function getN8nNodeByKey(key: string): N8nNodeCatalogEntry | undefined {
  return N8N_NODE_BY_KEY.get(key);
}

export function isKnownN8nNodeKey(key: string): key is N8nNodeKey {
  return N8N_NODE_BY_KEY.has(key);
}

export function getNodeSelectionPromptCatalog() {
  return N8N_NODE_CATALOG.map(
    ({
      key,
      displayName,
      description,
      capabilities,
      group,
      connectionRole,
      requiresAiModel,
    }) => ({
      key,
      displayName,
      description,
      capabilities,
      group,
      connectionRole,
      ...(requiresAiModel ? { requiresAiModel: true } : {}),
    }),
  );
}