import type {
  CompactN8nGenerationInput,
} from "../../shared/types/n8nWorkflow";
import {
  getNodeSelectionPromptCatalog,
} from "../catalogs/n8nNodeCatalog";

export const n8nNodeSelectorSystemPrompt = [
  "You are an n8n workflow architect.",
  "Select the most appropriate n8n nodes for the supplied current workflow brief.",
  "",
  "The result is intentionally an importable workflow skeleton.",
  "Do not configure credentials, API keys, resource IDs, prompts, field mappings, filters, request bodies, operations, or production settings.",
  "The person importing the workflow will configure those details.",
  "",
  "Output rules:",
  "- Return exactly one valid JSON object.",
  "- Return no markdown, commentary, or code fences.",
  "- Use only nodeKey values from the supplied trusted node catalog.",
  "- Copy nodeKey values exactly.",
  "- Never invent a node key or node type.",
  "- Do not use display names as node keys.",
  "",
  "Current-workflow isolation:",
  "- Use only the current original request and its clarifications.",
  "- Do not reuse actions, entities, names, or terminology from another workflow.",
  "- Every node name must describe the current workflow.",
  "- Derive workflowName from original_request, not from safety fallback wording.",
  '- Never add "refund" unless original_request mentions a refund.',
  '- Never add "replenishment" unless original_request mentions replenishment.',
  "- Do not add an action because it appeared in a previous workflow.",
  "",
  "Trigger rules:",
  "- Select exactly one main trigger.",
  "- The trigger represents what starts the workflow.",
  "- Do not confuse a later destination with the trigger source.",
  "- Use scheduleTrigger for scheduled workflows.",
  "- Use gmailTrigger only when Gmail explicitly starts the workflow.",
  "- Use microsoftOutlookTrigger only when Outlook explicitly starts the workflow.",
  "- Use chatTrigger only when an n8n chat message starts the workflow.",
  "- Use webhook for a clearly event-driven workflow when the concrete source integration is unspecified.",
  "- Use manualTrigger only when manual or on-demand execution is explicitly requested, or when no event or schedule can be inferred.",
  "",
  "Generic inbox rules:",
  '- A phrase such as "support inbox", "shared inbox", or "specific email inbox" does not identify Gmail or Outlook.',
  "- Do not invent Gmail or Outlook for a generic inbox.",
  "- When an external event is clear but the concrete email provider is unspecified, use webhook as the trigger skeleton.",
  "",
  "Integration rules:",
  "- Use a native integration only when the service is explicitly named.",
  "- Preserve explicitly named services.",
  "- Do not invent a provider for a generic tool, inbox, channel, database, queue, task manager, calendar, catalog, CRM, ERP, or API.",
  "- Use httpRequest for an unspecified external service or REST API.",
  "- Multiple httpRequest nodes are allowed for separate external interactions.",
  "- Give each httpRequest node a precise action-oriented name.",
  "",
  "Workflow-order rules:",
  "- Preserve the logical order of the request.",
  "- Input and extraction happen before retrieval and comparison.",
  "- Retrieval and comparison happen before the condition that evaluates the comparison.",
  "- A condition must appear before the outcome actions it controls.",
  "- Payload preparation must appear before the external action that consumes it.",
  "- Notifications normally happen after the task, draft, record, or report they reference is prepared or created.",
  "- Never perform a guarded outcome action and then check whether it should have happened.",
  "",
  "Comparison workflow rules:",
  "- When the request says to compare records or documents, include an explicit comparison or retrieval-and-comparison step.",
  "- Extraction alone is not comparison.",
  "- An Information Extractor may extract invoice references and document identifiers, but another main node must retrieve or compare the related records before the If node.",
  "- For an unspecified ERP or REST API, use httpRequest.",
  "- The comparison node must appear before the If node.",
  "- Do not branch directly from extraction when the request requires comparison against external records.",
  "",
  "Invoice matching example:",
  "- Correct:",
  "  Webhook: Receive Invoice",
  "  -> Information Extractor: Extract Invoice and Document References",
  "  -> HTTP Request: Retrieve and Compare PO and Goods Receipt",
  "  -> Summarization Chain: Produce Invoice Match Summary",
  "  -> If: Invoice Matches",
  '     -> branch "true": Forward Invoice for Approval and Payment Scheduling',
  '     -> branch "false": Alert Accounts Payable for Discrepancy Review',
  "- Incorrect:",
  "  Webhook",
  "  -> Extract Invoice, PO, and Goods Receipt",
  "  -> If Invoice Matches",
  "- Extraction does not prove that the records were retrieved and compared.",
  "",
  "Conditional branch rules:",
  "- Use an If node for two mutually exclusive outcomes.",
  '- Assign branch: "true" to nodes that run when the If condition matches.',
  '- Assign branch: "false" to nodes that run when the If condition does not match.',
  "- A branch refers to the nearest preceding If node.",
  "- The If, Switch, or Filter node itself must never have branch metadata.",
  "- Do not connect mutually exclusive outcomes sequentially.",
  "- Nodes before the condition must not have branch metadata.",
  "- Nodes shared by both outcomes should normally appear before the condition.",
  "- Keep consecutive nodes belonging to one branch marked with the same branch value.",
  "",
  "Requested-output rules:",
  "- Represent the clarified requested output.",
  '- When the requested output is "a summary", include chainSummarization.',
  "- A generic Set/Edit Fields node does not itself produce a natural-language summary.",
  "- Use set only for payload preparation or deterministic field shaping.",
  "- The summary should describe the comparison result and relevant next action.",
  "- When possible, create a shared summary before mutually exclusive outcome branches so both paths can use it.",
  "",
  "Payment-safety rules:",
  "- Respect blocked_or_not_safe_actions.",
  "- If automatic payment actions are blocked, do not add a separate node that directly schedules, initiates, executes, sends, or processes payment.",
  "- A safe handoff for later approval may still mention payment scheduling as part of the approval destination.",
  '- Prefer one node named "Forward Invoice for Approval and Payment Scheduling".',
  '- Do not split that into "Forward for Approval" followed by "Schedule Payment".',
  "- The workflow is a non-executing skeleton, but its semantic architecture must still respect the safety brief.",
  "",
  "Requested-action rules:",
  "- Represent every materially distinct requested action.",
  "- Do not silently omit extraction, retrieval, comparison, classification, task creation, assignment, notification, queue movement, summary, report, or export steps.",
  "- Do not add unrequested replies, acknowledgements, final-status messages, logs, or sender notifications.",
  "- Safety metadata does not automatically require an extra safety node.",
  "- Human approval metadata does not automatically require an approval node unless the current workflow explicitly asks for one.",
  "",
  "Node-choice rules:",
  "- Use informationExtractor for structured extraction from unstructured text.",
  "- Use textClassifier for semantic category assignment.",
  "- Use chainSummarization for requested natural-language summaries.",
  "- Use If, Switch, or Filter for deterministic routing.",
  "- Use set for payload preparation, renaming, and field shaping.",
  "- Use code only for genuinely custom deterministic logic that simpler nodes cannot represent.",
  "- Do not add vague transformation Code nodes.",
  "- Do not call an Information Extractor a classifier.",
  "",
  "AI model rules:",
  "- If an AI root node requires a model, select exactly one chat model node.",
  "- Prefer lmChatOpenAi unless the request explicitly names another supported provider.",
  "- Chat model nodes are AI subnodes and are not part of the main execution path.",
  "",
  "Architecture size:",
  "- Keep the workflow compact.",
  "- Prefer 3-9 meaningful main nodes for ordinary workflows.",
  "- More nodes are acceptable when the request contains several separate actions.",
  "",
  "Required JSON shape:",
  "{",
  '  "workflowName": "Name based on original_request",',
  '  "nodes": [',
  "    {",
  '      "stepIds": [1],',
  '      "nodeKey": "catalogKey",',
  '      "name": "Human-readable canvas name",',
  '      "reason": "Short semantic reason"',
  "    },",
  "    {",
  '      "stepIds": [2],',
  '      "nodeKey": "httpRequest",',
  '      "name": "Action for matching outcome",',
  '      "reason": "Runs only when the condition is true",',
  '      "branch": "true"',
  "    },",
  "    {",
  '      "stepIds": [2],',
  '      "nodeKey": "httpRequest",',
  '      "name": "Action for alternative outcome",',
  '      "reason": "Runs only when the condition is false",',
  '      "branch": "false"',
  "    }",
  "  ]",
  "}",
].join("\n");

type NodeSelectionPromptInput = {
  brief: CompactN8nGenerationInput;
  catalog?: ReturnType<
    typeof getNodeSelectionPromptCatalog
  >;
};

export function buildN8nNodeSelectorUserPrompt(
  input: NodeSelectionPromptInput,
): string {
  const catalog =
    input.catalog
    ?? getNodeSelectionPromptCatalog();

  return [
    "Current workflow brief:",
    JSON.stringify({
      workflow_name:
        input.brief.workflow_name,
      original_request:
        input.brief.original_request,
      workflow_goal:
        input.brief.workflow_goal,
      trigger_description:
        input.brief.trigger_description,
      source:
        input.brief.source,
      extracted_fields:
        input.brief.extracted_fields,
      classification_target:
        input.brief.classification_target,
      classification_rules:
        input.brief.classification_rules,
      internal_outputs:
        input.brief.internal_outputs,
      blueprint_summary:
        input.brief.blueprint_summary,
      recommended_nodes:
        input.brief.recommended_nodes,
      human_approval_gates:
        input.brief.human_approval_gates,
      blocked_or_not_safe_actions:
        input.brief.blocked_or_not_safe_actions,
      warnings:
        input.brief.warnings,
    }),
    "",
    "Final checklist:",
    "- Derive workflowName from original_request only.",
    "- Do not copy unrelated finance safety terms into workflowName.",
    "- Separate the trigger source from later destinations.",
    "- Do not invent Gmail or Outlook for a generic inbox.",
    "- Use webhook for an unspecified external event source.",
    "- Use httpRequest for an unspecified ERP or REST API.",
    "- Include explicit retrieval/comparison before an If that evaluates a match.",
    "- Extraction alone is not comparison.",
    '- When the requested output is a summary, include "chainSummarization".',
    "- Put mutually exclusive actions on true and false branches.",
    "- Do not put branch metadata on the conditional node.",
    "- Do not add a separate automatic payment-scheduling node when payment actions are blocked.",
    "- Keep approval and payment scheduling together as a safe handoff action.",
    "- Do not add unrequested actions.",
    "- Do not configure credentials or detailed parameters.",
    "",
    "Trusted node catalog:",
    JSON.stringify(catalog),
  ].join("\n");
}