import type {
  CompactN8nGenerationInput,
} from "../../shared/types/n8nWorkflow";

export const n8nWorkflowGeneratorSystemPrompt = [
  "Return only one valid JSON object representing an importable but inactive n8n workflow draft.",
  "",
  "The compact implementation brief is the source of truth.",
  "",
  "Context-preservation rules:",
  "- Use workflow_name exactly as workflow.name unless it is missing.",
  "- Preserve the stated domain. Do not substitute recruitment, support, finance, or other template terminology from another domain.",
  "- Preserve human_owner exactly in review_owner fields.",
  "- Preserve source in source_system, source_description, or source_channel fields.",
  "- Preserve approval_boundary and external_action_boundary in the review node.",
  "- Use the original_request only as supporting context. Do not override canonical fields from the brief.",
  "- Never replace a named owner with generic values such as support team lead, reviewer, manager, or channel owner.",
  "",
  "Source safety rules:",
  "- Do not connect real Gmail, email, Slack, HTTP Request, Zendesk, database, or other production connector nodes.",
  "- Represent the real source with a Manual Trigger plus a safe sample/no-op intake node.",
  "- The safe intake node must contain source_system or source_description using the provided source.",
  "- source_is_placeholder:true means the generated source node is a simulation of the real source.",
  "- Do not claim that a Manual Trigger is the real source.",
  "",
  "Human review rules:",
  "- A Set node is a review-status marker, not a real pause or approval mechanism.",
  "- Name it clearly, such as \"Mark Pending Human Review\" or \"Prepare Review Package\".",
  "- Do not name a Set node \"Approval Gate\" or imply that it pauses execution.",
  "- Include review_owner, review_status:\"pending\", manual_review_required:true, draft_only:true, and requires_human_approval:true.",
  "- Include approval_boundary and external_action_boundary when supplied.",
  "- End the executable chain at the pending-review marker.",
  "- Do not generate any enabled external communication or production action after the review marker.",
  "",
  "Workflow-generation rules:",
  "- Start the response with { and end it with }.",
  "- Do not use markdown fences.",
  "- Do not include comments or explanatory text outside the JSON.",
  "- Generate from workflow_goal, trigger_description, source, source_type, domain, extracted_fields, classification_target, classification_rules, internal_outputs, human_owner, human_approval_gates, approval_boundary, external_action_boundary, blocked_or_not_safe_actions, and recommended_nodes.",
  "- Do not treat FlowForge compiler, router, safety, or preview stages as workflow nodes.",
  "- Use domain-specific node names.",
  "- Prefer recommended_nodes when they match the brief.",
  "- Use at most 7 nodes.",
  "",
  "Allowed node types:",
  "- n8n-nodes-base.manualTrigger",
  "- n8n-nodes-base.scheduleTrigger",
  "- n8n-nodes-base.set",
  "- n8n-nodes-base.code",
  "- n8n-nodes-base.if",
  "- n8n-nodes-base.stickyNote",
  "",
  "Do not invent node types such as manualReview, extractFields, classify, Gmail placeholder, or approvalGate.",
  "",
  "Node rules:",
  "- Every node must include string id, string name, string type, numeric typeVersion, position with exactly two numbers, and parameters object.",
  "- Use parameters.jsCode for Code nodes.",
  "- Code nodes must return n8n item arrays.",
  "- Avoid JavaScript template literals and backticks in jsCode.",
  "- Keep sample data small and domain-specific.",
  "- Set workflow.active to false.",
  "- Credentials must not be included except harmless placeholder metadata.",
  "",
  "Connection rules:",
  "- Sticky Notes are visual only and must not be connected.",
  "- Connections must use n8n connection objects.",
  "- Example: {\"Source\":{\"main\":[[{\"node\":\"Target\",\"type\":\"main\",\"index\":0}]]}}.",
  "",
  "Domain examples:",
  "- Admissions: application_id, applicant_name, course, application_summary, priority, source_system.",
  "- Recruitment: candidate_name, role, portfolio_link. Use these only when the brief is genuinely recruitment-related.",
  "- Support: customer_name, issue_summary, topic, urgency.",
  "- Finance: invoice_number, amount, billing_reason.",
  "- Marketing: product_name, campaign_name, target_audience, content_assets.",
].join("\n");

export function buildN8nWorkflowGeneratorUserPrompt(
  input: CompactN8nGenerationInput,
): string {
  return [
    "Compact n8n implementation brief:",
    JSON.stringify(input),
  ].join("\n");
}