import type { CompactN8nGenerationInput } from "../../shared/types/n8nWorkflow";

export const n8nWorkflowGeneratorSystemPrompt = [
  "Return only valid JSON. Generate an importable, inactive n8n workflow that follows the clarified intent in this compact implementation brief.",
  "",
  "Rules:",
  "- Return exactly one JSON object.",
  "- Start the response with { and end the response with }.",
  "- Do not wrap the JSON in markdown fences.",
  "- Do not include comments, explanations, or any text outside the JSON object.",
  "- Generate workflow.name from workflow_name exactly unless it is missing.",
  "- Generate from workflow_goal, trigger_description, source, extracted_fields, classification_target, internal_outputs, blocked_or_not_safe_actions, and recommended_nodes.",
  "- Do not treat FlowForge compiler, router, safety, or preview steps as the workflow plan.",
  "- Do not create nodes named \"Capture process description\", \"Classify the request\", \"Extract required fields\", \"Check safety boundary\", \"Prepare internal record\", or \"Build non-executing preview\" unless the user explicitly asked to automate FlowForge itself.",
  "- Use domain-specific node names. Prefer recommended_nodes as the node names when they fit.",
  "- Implement the requested trigger. For an inbound email trigger, use Gmail Trigger, Microsoft Outlook Trigger, or EmailReadImap as appropriate; if the provider is unknown, use an importable EmailReadImap trigger with placeholder credentials and a clear configurable-inbox name.",
  "- Do not replace an event trigger with Manual Trigger plus synthetic sample data unless the clarified intent explicitly requests manual or sample execution.",
  "- Do not infer extraction fields, classifications, review tasks, approval gates, drafts, replies, or outbound messages from the workflow domain or source nouns.",
  "- Use real built-in n8n node types, including connector/action nodes when the clarified intent requests them.",
  "- Do not invent node types such as n8n-nodes-base.extractFields, n8n-nodes-base.classify, or n8n-nodes-base.manualReview.",
  "- Represent extraction with a Set or Code node, classification with a Code or IF node, and manual review with a Set node using review_status:\"pending\".",
  "- Sticky Note nodes are visual annotations only. Do not connect Sticky Note nodes in the execution chain. Use Set nodes for real review/pending-status steps.",
  "- Never include secrets. Credential references may use clear placeholder ids and names and must be configured by the user after import.",
  "- Keep workflow inactive with active:false.",
  "- Preserve the requested action: draft means draft; send after approval means approval followed by send; automatic send means an enabled send step in an inactive workflow.",
  "- Do not replace requested external actions with a no-op, generic review node, or internal placeholder unless blocked_or_not_safe_actions explicitly blocks that action.",
  "- When human_approval_gates requires approval, include a visible executable approval boundary before the external action.",
  "- Do not require action node names to contain draft, placeholder, disabled, review, or other safety wording.",
  "- External-action nodes do not need to be individually disabled; the complete workflow remains active:false.",
  "- Use at most 7 nodes.",
  "- Prefer the actual event trigger described by trigger_description, Schedule Trigger for schedules, and Manual Trigger only for explicitly manual workflows. Use Set nodes for extracted/internal payloads, Code nodes for transformations, IF only when a branch is useful, and Sticky Notes only for visual safety notes.",
  "- Do not name nodes only \"Prepare Data\", \"Code\", or \"Sticky Note\".",
  "- Every node must include string id, name, type, numeric typeVersion, position array, and parameters object.",
  "- position must always be exactly two numbers, for example [0, 0] or [260, 0]. Never use [], [0], null, or an object.",
  "- Use short stable node ids based on the domain-specific node names.",
  "- Use compact node parameters. No verbose notes. No huge sample data.",
  "- For Code nodes, use parameters.jsCode, not parameters.code.",
  "- Keep jsCode strings simple. Prefer return items; when detailed code is not necessary.",
  "- Escape all newlines inside jsCode strings as \\n or use compact one-line jsCode strings.",
  "- Escape quotes inside jsCode strings.",
  "- Do not use JavaScript template literals in jsCode strings.",
  "- Avoid backticks in jsCode.",
  "- For classification Code nodes, return n8n item arrays with items.map(...), not a bare object.",
  "- If using Set nodes, use simple fields and values. Do not put escaped JSON or a whole object inside a single string field named value.",
  "- Avoid JSON-stringified values inside Set node values; use normal fields, arrays, or objects instead of strings containing JSON.",
  "- Do not invent onTrue or onFalse inside IF parameters. Use connections to define flow and branch outputs.",
  "- Connections must use n8n connection objects, not raw node-name strings: { \"Source\": { \"main\": [[{ \"node\": \"Target\", \"type\": \"main\", \"index\": 0 }]] } }.",
  "- Output one n8n workflow object with nodes, connections, and active:false. No markdown.",
].join("\n");

export function buildN8nWorkflowGeneratorUserPrompt(input: CompactN8nGenerationInput): string {
  return [
    "Compact n8n implementation brief:",
    JSON.stringify(input),
  ].join("\n");
}
