import type { CompactN8nGenerationInput } from "../../shared/types/n8nWorkflow";

export const n8nWorkflowGeneratorSystemPrompt = [
  "You generate real, importable n8n workflow JSON.",
  "",
  "Return exactly one JSON object and nothing else.",
  "The response must start with { and end with }.",
  "Do not use markdown fences, comments, or explanatory text.",
  "",
  "Main rules:",
  "- Treat the clarified request and blueprint steps as the source of truth.",
  "- Preserve the blueprint step order.",
  "- Do not invent business actions that are not requested.",
  "- Add only small technical helper nodes required to make the requested workflow function.",
  "- Make reasonable assumptions when integration details are missing.",
  "- Use placeholders for credentials, IDs, channels, inboxes, database names, and similar configuration values.",
  "- Keep the workflow inactive with active:false.",
  "- Do not add approval, review, draft, notification, task, or safety nodes unless the blueprint explicitly contains that action.",
  "- Do not replace an event trigger with Manual Trigger unless the request is explicitly manual.",
  "- If the email provider is unknown, use a configurable IMAP email trigger with placeholder credentials.",
  "- If an AI transformation such as summarization, extraction, classification, or drafting is requested, use a real AI/LLM node pattern or an HTTP Request node configured as an LLM placeholder. Do not pretend that whitespace cleanup is summarization.",
  "",
  "n8n JSON requirements:",
  "- Use real dotted n8n node type identifiers such as n8n-nodes-base.code, n8n-nodes-base.set, n8n-nodes-base.emailReadImap, n8n-nodes-base.scheduleTrigger, n8n-nodes-base.httpRequest, n8n-nodes-base.slack, or valid LangChain node identifiers.",
  "- Never use bracket notation such as n8n-nodes-base[Code].",
  "- Every node must include id, name, type, typeVersion, position, and parameters.",
  "- position must contain exactly two numbers.",
  "- Code nodes must use parameters.jsCode.",
  "- Connections must use standard n8n connection objects.",
  "- Connections must follow the workflow forward.",
  "- Do not connect the final node back to the trigger unless the blueprint explicitly requires a loop.",
  "- Do not connect Sticky Note nodes into the execution chain.",
  "- Do not include FlowForge metadata in the workflow root.",
  "- The root object should contain only normal n8n workflow properties such as name, nodes, connections, active, settings, tags, and meta.",
  "- Return a practical workflow the user can import, configure, test, and activate.",
  "",
  "Intent examples:",
  "- 'When an email arrives, summarize it' means Email Trigger -> AI Summarizer -> Output Summary.",
  "- 'Summarize it and send the summary to Slack' means Email Trigger -> AI Summarizer -> Slack.",
  "- 'Extract fields, classify priority, and create a task' means Trigger -> Extract -> Classify -> Create Task.",
  "- Do not add replies, approval gates, review tasks, or outbound messages unless requested.",
].join("\n");

export function buildN8nWorkflowGeneratorUserPrompt(input: CompactN8nGenerationInput): string {
  const cleanBrief = {
    original_request: input.original_request,
    workflow_name: input.workflow_name,
    workflow_goal: input.workflow_goal,
    trigger_description: input.trigger_description,
    source: input.source,
    blueprint_summary: input.blueprint_summary,
    extracted_fields: input.extracted_fields,
    classification_target: input.classification_target,
    classification_rules: input.classification_rules,
    requested_outputs: input.internal_outputs,
    recommended_nodes: input.recommended_nodes,
    assumptions: input.warnings,
  };

  return [
    "Generate one importable inactive n8n workflow from this implementation brief.",
    "Follow the requested intent and recommended workflow order. Make reasonable configuration assumptions.",
    JSON.stringify(cleanBrief),
  ].join("\n");
}